### ISSUE TITLE
Proposal for using js bootcamp slide

### ISSUE THREAD

**Issue by eezhal92** [jhhayashi/bootcamp#1]
Hi Jordan, My name is Eezhal from Indonesia.

I watched your CS50 videos about js on youtube and it's really great!
I'd like to do the same thing for my friends or those who are beginner in js. And  i think it'd would be great if i can use your slides since it's so well organized. And if you're glad to help, where can i access the slides?

Thanks 😀!

**Comment by jhhayashi** [comment]
Hi Eezhal,

You're welcome to use the slides as long as you include an attribution! I've included scripts that link to the slides for most of the days, but it would probably be easiest to just access via the course website at http://www.jordanhayashi.com/bootcamp

**Comment by eezhal92** [comment]
Sure, i will include the attribution!

Thanks a lot!
