### ISSUE TITLE
Solutions for Day5 exercises?

### ISSUE THREAD

**Issue by smasetty** [jhhayashi/bootcamp#2]
Hi Jordan, 

Really love your lectures, can you please share the solutions for day5 exercises? TIA

ref: https://github.com/jhhayashi/bootcamp/tree/master/day5/morning/exercise 

Sharat

**Comment by jhhayashi** [comment]
Hi Sharat,

Since the exercises for that session were so open-ended, I didn't provide any solutions and fielded questions instead.  Feel free to leave a comment or submit a PR with your own solution though!
